spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first_db?currentSchema=database
    username: postgres
    password: 1488
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: database
  liquibase:
    change-log: classpath:/liquibase/db.changelog.yaml
    enabled: true
    default-schema: database

server:
  port: 9091
