spring:
  config:
    import: optional:file:.env
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
  liquibase:
    change-log: classpath:/liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}

server:
  port: 9091
